-- ============================================
-- Enrichment Consolidado: Segmentacion + Credits + Inversiones
-- ============================================
-- Combina las 4 fuentes de enriquecimiento en una sola tabla.
-- Para usar como job diario en Fury Dataflow.
-- Output: una fila por CUS_CUST_ID + TIM_MONTH + SIT_SITE_ID
-- ============================================

WITH MASTER AS (
    SELECT
        CUS_CUST_ID,
        CUST_SEGMENT_CROSS,
        SIT_SITE_ID,
        CAST(FORMAT_DATE("%Y%m", TIM_DAY) AS INT64) AS TIM_MONTH,
        TIM_DAY AS FECHA,
        MAX(TIM_DAY) AS MAX_PAY_DATE,
        MIN(TIM_DAY) AS MIN_PAY_DATE,
        ROUND(SUM(TPN_POINT),0) AS TPN_POINT,
        ROUND(SUM(TPN_QR),0) AS TPN_QR,
        ROUND(SUM(TPN_TRS),0) AS TPN_TRS,
        ROUND(SUM(TPN_OP_LINK),0) AS TPN_LINK,
        ROUND(SUM(TPN_OP_COW_API),0) AS TPN_API,
        ROUND(SUM(TPV_POINT_DOL),0) AS TPV_POINT,
        ROUND(SUM(TPV_QR_DOL),0) AS TPV_QR,
        ROUND(SUM(TPV_OP_COW_API_DOL),0) AS TPV_API,
        ROUND(SUM(TPV_OP_LINK_DOL),0) AS TPV_LINK
    FROM `meli-bi-data.WHOWNER.LK_MP_MASTER_SELLERS`
    WHERE TIM_DAY >= DATE_SUB(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 14 MONTH)
      AND TIM_DAY < DATE_TRUNC(CURRENT_DATE(), MONTH)
      AND SIT_SITE_ID IN ('MLA','MLB','MLM','MLC','MLU','MCO','MPE')
    GROUP BY 1,2,3,4,5
),

SELLERS_TRANSACTIONS AS (
    SELECT DISTINCT
        t.CUS_CUST_ID,
        SIT_SITE_ID,
        CAST(FORMAT_DATE("%Y%m", MAX_PAY_DATE) AS INT64) AS TIM_MONTH,
        TPN_POINT, TPN_TRS, TPN_QR, TPN_LINK, TPN_API,
        TPV_POINT, TPV_QR, TPV_API, TPV_LINK
    FROM MASTER t
    WHERE TPN_POINT > 0 OR TPN_TRS > 0 OR TPN_QR > 0 OR TPN_LINK > 0 OR TPN_API > 0
),

SEGMENTATION_SELLERS AS (
    SELECT DISTINCT
        t.CUS_CUST_ID,
        t.SIT_SITE_ID,
        t.TIM_MONTH AS TIM_MONTH_TRANSACTION,
        CASE WHEN TPN_POINT > 0 THEN 1 ELSE 0 END AS POINT_FLAG,
        CASE WHEN TPN_TRS > 0 THEN 1 ELSE 0 END AS TRANSF_FLAG,
        CASE WHEN TPN_QR > 0 THEN 1 ELSE 0 END AS QR_FLAG,
        CASE WHEN TPN_LINK > 0 THEN 1 ELSE 0 END AS LINK_FLAG,
        CASE WHEN TPN_API > 0 THEN 1 ELSE 0 END AS API_FLAG,
        t.TPN_POINT, t.TPN_TRS, t.TPN_QR, t.TPN_LINK, t.TPN_API,
        t.TPV_POINT, t.TPV_QR, t.TPV_API, t.TPV_LINK,
        s.CUST_SEGMENT_CROSS AS SEGMENTO,
        s.CUST_SUB_SEGMENT_CROSS AS SUB_SEGMENTO,
        s.CUST_TYPE AS TIPO_SELLER,
        s.NEW_MAS_FLAG,
        s.TIM_MONTH AS TIM_MONTH_SEGMENTATION,
        CASE
            WHEN s.CUST_PRODUCT_DETAIL = 'OP_COW_API' THEN 'APICOW'
            WHEN s.CUST_PRODUCT_DETAIL = 'OP_LINK' THEN 'LINK'
            ELSE s.CUST_PRODUCT_DETAIL
        END AS PRODUCTO,
        CASE
            WHEN B.KYC_ENTITY_TYPE = 'person' THEN 'PF'
            WHEN B.KYC_ENTITY_TYPE = 'company' THEN 'PJ'
            ELSE B.KYC_ENTITY_TYPE
        END AS PERSON
    FROM SELLERS_TRANSACTIONS t
    INNER JOIN `meli-bi-data.WHOWNER.LK_MP_SEGMENTATION_SELLERS` s
        ON t.CUS_CUST_ID = s.CUS_CUST_ID
        AND t.TIM_MONTH >= s.TIM_MONTH
        AND s.SELL_ACTIVE_MTD_FLAG = 1
    LEFT JOIN `meli-bi-data.WHOWNER.LK_KYC_VAULT_USER` B
        ON B.CUS_CUST_ID = s.CUS_CUST_ID
    QUALIFY ROW_NUMBER() OVER(PARTITION BY t.CUS_CUST_ID, t.TIM_MONTH ORDER BY s.TIM_MONTH DESC) = 1
),

-- Segmentacion base con flags derivados
seg_enriched AS (
    SELECT
        s.CUS_CUST_ID,
        s.SIT_SITE_ID,
        s.TIM_MONTH_TRANSACTION AS TIM_MONTH,
        s.POINT_FLAG, s.TRANSF_FLAG, s.QR_FLAG, s.LINK_FLAG, s.API_FLAG,
        s.TPN_POINT, s.TPN_TRS, s.TPN_QR, s.TPN_LINK, s.TPN_API,
        s.TPV_POINT, s.TPV_QR, s.TPV_API, s.TPV_LINK,
        s.SEGMENTO, s.SUB_SEGMENTO, s.TIPO_SELLER,
        s.NEW_MAS_FLAG, s.PRODUCTO, s.PERSON,

        -- PRODUCTO_PRINCIPAL
        CASE
            WHEN s.PRODUCTO = 'POINT' THEN 'Point'
            WHEN s.PRODUCTO = 'QR' THEN 'QR'
            WHEN s.PRODUCTO IN ('LINK','APICOW') THEN 'OP'
            WHEN s.PRODUCTO = 'TRANSFERENCIAS' THEN 'Transferencias'
            ELSE 'Otro'
        END AS PRODUCTO_PRINCIPAL,

        -- NEWBIE_LEGACY
        CASE
            WHEN s.NEW_MAS_FLAG = 1 THEN 'Newbie'
            WHEN s.NEW_MAS_FLAG = 0 THEN 'Legacy'
            ELSE 'Sin dato'
        END AS NEWBIE_LEGACY,

        -- PF_PJ (alias limpio)
        s.PERSON AS PF_PJ,

        -- USO_PRODUCTOS
        CASE WHEN s.POINT_FLAG + s.TRANSF_FLAG + s.QR_FLAG + s.LINK_FLAG + s.API_FLAG > 1
            THEN 'COMPARTIDO' ELSE 'UNICO'
        END AS USO_PRODUCTOS,

        -- OP_FLAG
        CASE WHEN s.LINK_FLAG >= 1 OR s.API_FLAG >= 1 THEN 1 ELSE 0 END AS OP_FLAG,

        -- TPN_TOTAL / TPV_TOTAL
        COALESCE(s.TPN_POINT,0) + COALESCE(s.TPN_QR,0) + COALESCE(s.TPN_LINK,0) + COALESCE(s.TPN_API,0) + COALESCE(s.TPN_TRS,0) AS TPN_TOTAL,
        COALESCE(s.TPV_POINT,0) + COALESCE(s.TPV_QR,0) + COALESCE(s.TPV_LINK,0) + COALESCE(s.TPV_API,0) AS TPV_TOTAL,

        -- RANGO_TPN
        CASE
            WHEN COALESCE(s.TPN_POINT,0)+COALESCE(s.TPN_QR,0)+COALESCE(s.TPN_LINK,0)+COALESCE(s.TPN_API,0)+COALESCE(s.TPN_TRS,0) = 0 THEN '0 txn'
            WHEN COALESCE(s.TPN_POINT,0)+COALESCE(s.TPN_QR,0)+COALESCE(s.TPN_LINK,0)+COALESCE(s.TPN_API,0)+COALESCE(s.TPN_TRS,0) BETWEEN 1 AND 10 THEN '1-10 txn'
            WHEN COALESCE(s.TPN_POINT,0)+COALESCE(s.TPN_QR,0)+COALESCE(s.TPN_LINK,0)+COALESCE(s.TPN_API,0)+COALESCE(s.TPN_TRS,0) BETWEEN 11 AND 50 THEN '11-50 txn'
            WHEN COALESCE(s.TPN_POINT,0)+COALESCE(s.TPN_QR,0)+COALESCE(s.TPN_LINK,0)+COALESCE(s.TPN_API,0)+COALESCE(s.TPN_TRS,0) BETWEEN 51 AND 200 THEN '51-200 txn'
            WHEN COALESCE(s.TPN_POINT,0)+COALESCE(s.TPN_QR,0)+COALESCE(s.TPN_LINK,0)+COALESCE(s.TPN_API,0)+COALESCE(s.TPN_TRS,0) BETWEEN 201 AND 1000 THEN '201-1000 txn'
            ELSE '1000+ txn'
        END AS RANGO_TPN,

        -- RANGO_TPV
        CASE
            WHEN COALESCE(s.TPV_POINT,0)+COALESCE(s.TPV_QR,0)+COALESCE(s.TPV_LINK,0)+COALESCE(s.TPV_API,0) = 0 THEN '$0'
            WHEN COALESCE(s.TPV_POINT,0)+COALESCE(s.TPV_QR,0)+COALESCE(s.TPV_LINK,0)+COALESCE(s.TPV_API,0) BETWEEN 1 AND 100 THEN '$1-100'
            WHEN COALESCE(s.TPV_POINT,0)+COALESCE(s.TPV_QR,0)+COALESCE(s.TPV_LINK,0)+COALESCE(s.TPV_API,0) BETWEEN 101 AND 500 THEN '$101-500'
            WHEN COALESCE(s.TPV_POINT,0)+COALESCE(s.TPV_QR,0)+COALESCE(s.TPV_LINK,0)+COALESCE(s.TPV_API,0) BETWEEN 501 AND 2000 THEN '$501-2K'
            WHEN COALESCE(s.TPV_POINT,0)+COALESCE(s.TPV_QR,0)+COALESCE(s.TPV_LINK,0)+COALESCE(s.TPV_API,0) BETWEEN 2001 AND 10000 THEN '$2K-10K'
            ELSE '$10K+'
        END AS RANGO_TPV

    FROM SEGMENTATION_SELLERS s
    WHERE s.PERSON IN ('PF', 'PJ')
      AND s.PRODUCTO IN ('POINT', 'QR', 'TRANSFERENCIAS', 'LINK', 'APICOW')
      AND s.SEGMENTO NOT IN ('BIG SELLERS')
),

-- Credits
credits_agg AS (
    SELECT
        f.CUS_CUST_ID,
        CAST(f.TIM_MONTH AS INT64) AS TIM_MONTH,
        f.CREDIT_GROUP,
        CASE
            WHEN COALESCE(f.PRODUCT_USED.MERCHANT_CREDIT, 0) > 0
              OR COALESCE(f.PRODUCT_USED.CONSUMER_CREDIT, 0) > 0
              OR COALESCE(f.PRODUCT_USED.PERSONAL_LOAN, 0) > 0
              OR COALESCE(f.PRODUCT_USED.SECURED_LOAN, 0) > 0
            THEN 'Usa crédito'
            ELSE 'No usa crédito'
        END AS FLAG_USA_CREDITO,
        CASE
            WHEN COALESCE(f.PRODUCT_USED.CREDIT_CARD, 0) > 0
            THEN 'Tiene TC MP'
            ELSE 'Sin TC MP'
        END AS FLAG_TARJETA_CREDITO,
        CASE
            WHEN f.FLAG_OFFER_CREDITS = 1 AND COALESCE(f.PRODUCT_USED.MERCHANT_CREDIT, 0) = 0
                 AND COALESCE(f.PRODUCT_USED.PERSONAL_LOAN, 0) = 0
            THEN 'Oferta no tomada'
            WHEN f.FLAG_OFFER_CREDITS = 1 THEN 'Oferta tomada'
            ELSE 'Sin oferta'
        END AS ESTADO_OFERTA_CREDITO
    FROM `meli-bi-data.WHOWNER.LK_MP_MAUS_CREDIT_PROFILE` f
    WHERE CAST(f.TIM_MONTH AS INT64) >= CAST(FORMAT_DATE("%Y%m", DATE_SUB(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 14 MONTH)) AS INT64)
      AND CAST(f.TIM_MONTH AS INT64) <= CAST(FORMAT_DATE("%Y%m", DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) AS INT64)
),

-- Inversiones
inversiones_agg AS (
    SELECT
        a.CUS_CUST_ID,
        a.SIT_SITE_ID,
        CAST(FORMAT_DATE('%Y%m', a.TIM_DAY) AS INT64) AS TIM_MONTH,
        MAX(CASE WHEN a.POTS_ACTIVE_QTY > 0 THEN 1 ELSE 0 END) AS FLAG_POTS_ACTIVO,
        MAX(a.POTS_ACTIVE_QTY) AS POTS_CANTIDAD,
        CASE
            WHEN MAX(CASE WHEN a.POTS_ACTIVE_QTY > 0 THEN 1 ELSE 0 END) = 1
            THEN 'Usa inversiones'
            ELSE 'No usa inversiones'
        END AS FLAG_USA_INVERSIONES
    FROM `meli-bi-data.WHOWNER.DM_MP_INVESTMENTS` a
    WHERE a.TIM_DAY >= DATE_SUB(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 14 MONTH)
      AND a.TIM_DAY < DATE_TRUNC(CURRENT_DATE(), MONTH)
      AND a.SIT_SITE_ID IN ('MLA','MLB','MLM','MLC','MLU','MCO','MPE')
    GROUP BY 1, 2, 3
)

-- Final: JOIN todo
SELECT
    seg.CUS_CUST_ID,
    seg.SIT_SITE_ID,
    seg.TIM_MONTH,
    seg.POINT_FLAG,
    seg.TRANSF_FLAG,
    seg.QR_FLAG,
    seg.LINK_FLAG,
    seg.API_FLAG,
    seg.TPN_POINT, seg.TPN_TRS, seg.TPN_QR, seg.TPN_LINK, seg.TPN_API,
    seg.TPV_POINT, seg.TPV_QR, seg.TPV_API, seg.TPV_LINK,
    seg.TPN_TOTAL, seg.TPV_TOTAL,
    seg.SEGMENTO, seg.SUB_SEGMENTO, seg.TIPO_SELLER,
    seg.NEW_MAS_FLAG, seg.PRODUCTO, seg.PERSON, seg.PF_PJ,
    seg.PRODUCTO_PRINCIPAL, seg.NEWBIE_LEGACY,
    seg.USO_PRODUCTOS, seg.OP_FLAG,
    seg.RANGO_TPN, seg.RANGO_TPV,

    -- Credits
    cr.CREDIT_GROUP,
    COALESCE(cr.FLAG_USA_CREDITO, 'Sin dato credits') AS FLAG_USA_CREDITO,
    COALESCE(cr.FLAG_TARJETA_CREDITO, 'Sin dato credits') AS FLAG_TARJETA_CREDITO,
    COALESCE(cr.ESTADO_OFERTA_CREDITO, 'Sin dato credits') AS ESTADO_OFERTA_CREDITO,

    -- Inversiones
    COALESCE(inv.FLAG_POTS_ACTIVO, 0) AS FLAG_POTS_ACTIVO,
    inv.POTS_CANTIDAD,
    COALESCE(inv.FLAG_USA_INVERSIONES, 'Sin dato inversiones') AS FLAG_USA_INVERSIONES

FROM seg_enriched seg
LEFT JOIN credits_agg cr
    ON seg.CUS_CUST_ID = cr.CUS_CUST_ID
    AND seg.TIM_MONTH = cr.TIM_MONTH
LEFT JOIN inversiones_agg inv
    ON seg.CUS_CUST_ID = inv.CUS_CUST_ID
    AND seg.SIT_SITE_ID = inv.SIT_SITE_ID
    AND seg.TIM_MONTH = inv.TIM_MONTH
