-- ==========================================
-- Query principal para OP (LINK / APICOW)
-- ==========================================
-- Replica exactamente la query de referencia del Excel de OP.
-- Incluye join directo con WHOWNER.BT_RES_RESTRICTIONS_SENTENCES y flag CONSIDERACION_AJUSTADA.
-- No requiere tabla materializada RESTRICTIONS_SELLERS ni enrichment_restricciones.sql.
-- Filtro: NPS_TX_NOTA_NPS IS NOT NULL.
-- QUALIFY deduplica por response_id después del join de restricciones.
-- Parámetros:
--   {sites}, {fecha_minima}, {fecha_maxima}, {e_code_filter}

SELECT
    -- Identificadores
    NPS_TX_SIT_SITE_ID AS SITE,
    CAST(NPS_TX_END_DATE AS TIMESTAMP) AS END_DATE,
    EXTRACT(YEAR FROM NPS_TX_END_DATE) AS YEAR,
    EXTRACT(QUARTER FROM NPS_TX_END_DATE) AS QUARTER,
    FORMAT_DATE("%Y%m", NPS_TX_END_DATE) AS END_DATE_MONTH,
    EXTRACT(WEEK FROM NPS_TX_END_DATE) AS WEEK,
    CAST(NPS_TX_QUALTRICS_RESPONSE_ID AS STRING) AS SURVEY_ID,
    NPS_TX_CUS_CUST_ID AS CUST_ID,
    NPS_TX_CUS_CUST_ID AS SELLER_ID,

    -- NPS (campo NPS de la tabla, no calculado)
    NPS_TX_NOTA_NPS AS NOTA_NPS,
    CASE
        WHEN NPS_TX_NOTA_NPS IS NULL THEN NULL
        WHEN NPS_TX_NOTA_NPS IN (9, 10) THEN 1
        WHEN NPS_TX_NOTA_NPS IN (7, 8) THEN 0
        WHEN NPS_TX_NOTA_NPS IN (0, 1, 2, 3, 4, 5, 6) THEN -1
    END AS NPS,

    -- Motivos originales
    NPS_TX_MPROM AS PROMOTION_REASON_NPS,
    NPS_TX_MNEUTRO AS NEUTRAL_REASON_NPS,
    NPS_TX_MDET AS DETRACTION_REASON_NPS,
    NPS_TX_COMMENT AS COMMENTS,

    -- MOTIVO unificado
    CASE
        WHEN NPS_TX_NOTA_NPS IN (9, 10) THEN COALESCE(NPS_TX_MPROM, 'Sin información')
        WHEN NPS_TX_NOTA_NPS IN (7, 8) THEN COALESCE(NPS_TX_MNEUTRO, 'Sin información')
        WHEN NPS_TX_NOTA_NPS IN (0, 1, 2, 3, 4, 5, 6) THEN COALESCE(NPS_TX_MDET, 'Sin información')
        ELSE 'Sin información'
    END AS MOTIVO,

    -- Segmentación
    SEGMENTO_TAMANO_SELLER,
    SEGMENTO_CROSSMP,
    POINT_DEVICE_TYPE,

    -- Device Point
    MODELO_DEVICE,
    NPS_TX_DEVICE_DECLARADO AS DEVICE_DECLARADO,
    NPS_POINT_ADQ_CHANNEL AS CANAL_ADQUISICION,

    -- Problemas de funcionamiento
    NPS_TX_PROBLEMA_FUNCIONAMIENTO AS PROBLEMA_FUNCIONAMIENTO,
    NPS_TX_PROBLEMA_BLOQUEANTE AS PROBLEMA_BLOQUEANTE,
    NPS_TX_TIPO_PROBLEMA_FUNCIONAMIENTO AS TIPO_PROBLEMA,

    -- Valoraciones device
    NPS_TX_VALORAC_BLUETOOTH AS VALORAC_BLUETOOTH,
    NPS_TX_VALORAC_CHIP AS VALORAC_CHIP,
    NPS_TX_VALORAC_WIFI AS VALORAC_WIFI,
    NPS_TX_VALORAC_MEDIO_PAGO AS VALORAC_MEDIO_PAGO,
    NPS_TX_VALORAC_LECTURA AS VALORAC_LECTURA,
    NPS_TX_VALORAC_PROCESAMIENTO AS VALORAC_PROCESAMIENTO,
    NPS_TX_VALORAC_SEGURIDAD AS VALORAC_SEGURIDAD,
    NPS_TX_VALORAC_BATERIA AS VALORAC_BATERIA,
    NPS_TX_VALORAC_COMPROBANTES AS VALORAC_COMPROBANTES,
    NPS_TX_VALORAC_CONECTIVIDAD AS VALORAC_CONECTIVIDAD,

    -- Flags de uso de productos
    POINT_USER,
    QR_USER,
    OP_USER,
    FLAG_APICOW,
    FLAG_PIX,
    USO_PRODUCTOS,

    -- FLAG_PIX_F
    CASE
        WHEN USO_PRODUCTOS = 'UNICO' AND NPS_TX_E_CODE LIKE '%TRANSFERENCIAS%' THEN 'OnlyTRF'
        ELSE 'ST'
    END AS FLAG_PIX_F,

    -- E_CODE y PF_PJ
    NPS_TX_E_CODE AS E_CODE,
    CAST(NULL AS STRING) AS PF_PJ,

    -- Producto OP derivado
    CASE
        WHEN r.NPS_TX_E_CODE LIKE '%LINK%' THEN 'LINK'
        WHEN r.NPS_TX_E_CODE LIKE '%API%' THEN 'APICOW'
        ELSE 'OTHER'
    END AS PRODUCTO_OP,

    -- Restricciones (join directo con BT_RES_RESTRICTIONS_SENTENCES)
    MAX(RR.COLOR_DE_TARJETA) OVER (PARTITION BY NPS_TX_QUALTRICS_RESPONSE_ID) AS COLOR_DE_TARJETA,
    MAX(
        CASE WHEN RR.SENTENCE_ID IS NULL THEN 0 ELSE 1 END
    ) OVER (PARTITION BY NPS_TX_QUALTRICS_RESPONSE_ID) AS USER_RESTRICCION,
    MIN(
        CASE
            WHEN RR.COLOR_DE_TARJETA IN ('2', '3')
                AND (
                    RR.SENTENCE_REHABILITATION_DATE IS NULL
                    OR RR.SENTENCE_REHABILITATION_DATE >= r.NPS_TX_END_DATE
                )
            THEN 0
            ELSE 1
        END
    ) OVER (PARTITION BY NPS_TX_QUALTRICS_RESPONSE_ID) AS CONSIDERACION_AJUSTADA,

    -- Comentario de funcionamiento
    PROBLEMA_FUNCIONAMIENTO_COMMENT,
    ANTIGUEDAD

FROM `meli-bi-data.SBOX_CX_BI_ADS_CORE.BT_NPS_TX_SELLERS_MP_DETAIL` r

-- Join directo con tabla de restricciones (sin tabla materializada intermedia)
LEFT JOIN `WHOWNER.BT_RES_RESTRICTIONS_SENTENCES` RR
    ON RR.user_id = r.NPS_TX_CUS_CUST_ID
    AND r.NPS_TX_END_DATE >= RR.SENTENCE_DATE
    AND RR.SENTENCE_DATE >= DATE_SUB(r.NPS_TX_END_DATE, INTERVAL 6 MONTH)

WHERE 1=1
    AND r.NPS_TX_END_DATE >= '{fecha_minima}'
    AND r.NPS_TX_END_DATE < '{fecha_maxima}'
    AND r.NPS_TX_SIT_SITE_ID IN {sites}
    AND r.NPS_TX_NOTA_NPS IS NOT NULL
    {e_code_filter}

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY NPS_TX_QUALTRICS_RESPONSE_ID
    ORDER BY NPS_TX_END_DATE DESC, RR.SENTENCE_DATE DESC
) = 1
